networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.53.0.0/24


services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - TOKEN
      - SUBDOMAINS=gparrello
      - TZ=Europe/Madrid
      - CONTAINER_DATA_PATH=/home/gerardo/.container-data/wirehole
    volumes:
      - ${CONTAINER_DATA_PATH}/duckdns/config:/config

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    environment:
      - CONTAINER_DATA_PATH=/home/gerardo/.container-data/wirehole
    volumes:
      - ${CONTAINER_DATA_PATH}/unbound:/opt/unbound/etc/unbound/
    networks:
      private_network:
        ipv4_address: 10.53.0.200
    cap_add:
      - NET_ADMIN

  wireguard:
    depends_on:
      - duckdns
      - unbound
      - pihole
    image: linuxserver/wireguard
    container_name: wireguard
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ${CONTAINER_DATA_PATH}/config:/config
    environment:
      - CONTAINER_DATA_PATH=/home/gerardo/.container-data/wirehole

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${CONTAINER_DATA_PATH}/db:/app/db
      - ${CONTAINER_DATA_PATH}/config:/config
    environment:
      - WGUI_DNS=10.53.0.100
      - SUBNET_RANGES=10.80.1.0/24
      - WGUI_ENDPOINT_ADDRESS=gparrello.duckdns.org:51888
      - CONTAINER_DATA_PATH=/home/gerardo/.container-data/wirehole

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS_}
    volumes:
      - ${CONTAINER_DATA_PATH}/etc-pihole/:/etc/pihole/
      - ${CONTAINER_DATA_PATH}/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.53.0.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "5380:80"
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=admin
      - PIHOLE_DNS_=10.53.0.200
      - DNSSEC=true
